version: 2
before:
  hooks:
    - go mod download
    - go mod verify

env:
  - GO111MODULE=on
  - BECH32_PREFIX="mock"
  - BUILD_TAGS=cgo,netgo,ledger

builds:
  - id: "rollappd-darwin"
    main: ./cmd/rollappd
    binary: rollappd
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags={{.Env.BUILD_TAGS}}
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=dymension-rdk
      - -X github.com/cosmos/cosmos-sdk/version.AppName=rollapp-evm
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags={{.Env.BUILD_TAGS}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/tendermint/tendermint/version.TMCoreSemVer={{.Env.TM_VERSION}}
      - -X github.com/dymensionxyz/rollapp-evm/app.AccountAddressPrefix={{.Env.BECH32_PREFIX}}
      - -X github.com/dymensionxyz/dymension-rdk/x/rollappparams/types.Version={{.Commit}}
      - -X github.com/dymensionxyz/dymint/version.Commit={{.Commit}}
  - id: "rollappd-darwin-arm64"
    main: ./cmd/rollappd
    binary: rollappd
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -tags={{.Env.BUILD_TAGS}}
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=dymension-rdk
      - -X github.com/cosmos/cosmos-sdk/version.AppName=rollapp-evm
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags={{.Env.BUILD_TAGS}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/tendermint/tendermint/version.TMCoreSemVer={{.Env.TM_VERSION}}
      - -X github.com/dymensionxyz/rollapp-evm/app.AccountAddressPrefix={{.Env.BECH32_PREFIX}}
      - -X github.com/dymensionxyz/dymension-rdk/x/rollappparams/types.Version={{.Commit}}
      - -X github.com/dymensionxyz/dymint/version.Commit={{.Commit}}
  - id: "rollappd-linux"
    main: ./cmd/rollappd
    binary: rollappd
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags={{.Env.BUILD_TAGS}}
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=dymension-rdk
      - -X github.com/cosmos/cosmos-sdk/version.AppName=rollapp-evm
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags={{.Env.BUILD_TAGS}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/tendermint/tendermint/version.TMCoreSemVer={{.Env.TM_VERSION}}
      - -X github.com/dymensionxyz/rollapp-evm/app.AccountAddressPrefix={{.Env.BECH32_PREFIX}}
      - -X github.com/dymensionxyz/dymension-rdk/x/rollappparams/types.Version={{.Commit}}
      - -X github.com/dymensionxyz/dymint/version.Commit={{.Commit}}
  - id: "rollappd-linux-arm64"
    main: ./cmd/rollappd
    binary: rollappd
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags={{.Env.BUILD_TAGS}}
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=dymension-rdk
      - -X github.com/cosmos/cosmos-sdk/version.AppName=rollapp-evm
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags={{.Env.BUILD_TAGS}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/tendermint/tendermint/version.TMCoreSemVer={{.Env.TM_VERSION}}
      - -X github.com/dymensionxyz/rollapp-evm/app.AccountAddressPrefix={{.Env.BECH32_PREFIX}}
      - -X github.com/dymensionxyz/dymension-rdk/x/rollappparams/types.Version={{.Commit}}
      - -X github.com/dymensionxyz/dymint/version.Commit={{.Commit}}
#  - id: "rollappd-windows"
#    main: ./cmd/rollappd
#    binary: rollappd
#    env:
#      - CGO_ENABLED=1
#      - CC=x86_64-w64-mingw32-gcc
#      - CXX=x86_64-w64-mingw32-g++
#    goos:
#      - windows
#    goarch:
#      - amd64
#    flags:
#      - -tags={{.Env.BUILD_TAGS}}
#      - -buildmode=exe
#    ldflags:
#      - -s -w
#      - -X github.com/cosmos/cosmos-sdk/version.Name=dymension-rdk
#      - -X github.com/cosmos/cosmos-sdk/version.AppName=rollapp-evm
#      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
#      - -X github.com/cosmos/cosmos-sdk/version.BuildTags={{.Env.BUILD_TAGS}}
#      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
#      - -X github.com/tendermint/tendermint/version.TMCoreSemVer={{.Env.TM_VERSION}}
#      - -X github.com/dymensionxyz/rollapp-evm/app.AccountAddressPrefix={{.Env.BECH32_PREFIX}}
#      - -X github.com/dymensionxyz/dymension-rdk/x/rollappparams/types.Version={{.Commit}}
#      - -X github.com/dymensionxyz/dymint/version.Commit={{.Commit}}

archives:
  - name_template: '{{ .ProjectName }}_{{- title .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - rollappd-darwin
      - rollappd-darwin-arm64
      - rollappd-windows
      - rollappd-linux
      - rollappd-linux-arm64

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
snapshot:
  name_template: "{{ .Tag }}-next"