name: Build Rollappd
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux]
        go-version: ['1.21.x', '1.22.x']
        include:
          - targetos: darwin
            arch: arm64
    name: rollapp ${{ matrix.arch }} for ${{ matrix.targetos }} with Go ${{ matrix.go-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile rollappd
        run: |
          go mod download
          cd cmd/rollappd
          go build .

      - name: Install Dasel
        run: |
          curl -sSLf https://github.com/TomWright/dasel/releases/latest/download/dasel_${{ matrix.targetos }}_${{ matrix.arch }} -o /usr/local/bin/dasel
          chmod +x /usr/local/bin/dasel
          
      - name: Generate genesis template mainnet
        run: make generate-genesis env=mainnet
        env:
          BECH32_PREFIX: ethm
      
      - name: Generate genesis template testnet
        run: make generate-genesis env=testnet
        env:
          BECH32_PREFIX: ethm

      - uses: actions/upload-artifact@v3
        with:
          name: rollappd ${{ matrix.targetos }} ${{ matrix.arch }} Go ${{ matrix.go-version }}
          path: cmd/rollappd/rollappd
